name: flask-app-test

dependencies:
  - python==3.7.6
  - flask==1.1.2
  - flask_sqlalchemy==2.4.4
  - flask_restful==0.3.8
  - flask_jwt_extended==3.25.0
  - flask_bcrypt==0.7.1
  - pandas==1.1.4
  - psycopg2==2.8.6
  - pytest==6.2.1
